server:
  port: 8089
spring:
  datasource:
   url: jdbc:mysql://134.175.171.235:3306/z_weixiao?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
   username: root
   password: mysql5.7
   driver-class-name: com.mysql.jdbc.Driver
#  jackson:
#   date-format: yyyy-MM-dd HH:mm:ss
#   time-zone: GMT+8
#   locale: zh_CN
  jpa:
   show-sql: true

# Swagger
swagger:
  host: 127.0.0.1
  title: weixiao
  description: Campus communication
  disabled: false # 是否禁用swagger
  redirect-uri: / # 禁用swagger时的重定向地址
project:
  version: 1.0.0
