server:
  port: 6004
spring:
  datasource:
    url: jdbc:mysql://134.175.171.235:3306/z_weixiao?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql5.7
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true